### ISSUE TITLE
Can you add upsert mode to replace existing documents?

### ISSUE THREAD

**Issue by truongtv22** [lihaibh/mongodb-snapshot#11]
It's like mongoimport 😃

**Comment by lihaibh** [comment]
basically when you configure a target connector you can provide a boolean to determine whether or not you want to perform cleanup.
so if you do not perform cleanup it will just add more documents to it.
but in case of a duplicated key you will receive an error.

can you open a Pull Request?

**Comment by lihaibh** [comment]
@truongtv22 
are you working on it or can you give more details of what you are trying to achieve?
this issue is open for almost a month without any progress.
