### ISSUE TITLE
Database import does not work.

### ISSUE THREAD

**Issue by TeacherSpaceSchool** [lihaibh/mongodb-snapshot#12]
I am trying to update a DB with a previously created backup. To do this, I use the *remove_on_startup* field, but I still receive a duplicate key error.

**Comment by lihaibh** [comment]
@TeacherSpaceSchool you created the backup with this library?

**Comment by lihaibh** [comment]
@TeacherSpaceSchool can you provide more information regarding the error or shall i close the issue?
