### ISSUE TITLE
View bson File

### ISSUE THREAD

**Issue by danielehrhardt** [lihaibh/mongodb-snapshot#14]
Hi,
i really like this Package. Thank you!
Is the a way to extract the .tar File and View the bson Files?
Sometimes it is good to check if the Date is like we need before a restore.

Best,
Daniel

**Comment by lihaibh** [comment]
in order to extract the tar file you can run the command:
```
tar -xvf ./dump.tar -C ./mydir
```

**Comment by danielehrhardt** [comment]
Ah, sorry I saw that my Equation is a bit confusing. I mean how to open the bson File. I tried it with several File Editors but there is only wired output.

**Comment by lihaibh** [comment]
bson is binary json i think there are tools that can help you convert bson to json, try to look for `bsondump`

**Comment by danielehrhardt** [comment]
Thank you!
